typography_spectrum: 0.3320798077620566
color:
  brandStrength: 0.42050231737084687
  lightness: 0.737168911844492
  saturation: 0.2431596708483994
  rhythmicContrast: 0.17575015616603196
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.26068859943188727
author:
  name: Victoria Rosa
  email: victoria@openandawesome.co.uk
  url: www.yourconsciousrelationship.com
name: Your Conscious Relationships
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/27e1273e-e8b9-4901-971c-21452878e832.png
title: 'Healthy, Happy, Aware'
description: Applying the lessons of polyamory to all kinds of relationships
